# Generated by Django 4.0.2 on 2022-03-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='profile',
            field=models.ManyToManyField(through='user.InterestStatus', to='user.Profile'),
        ),
    ]
