# Generated by Django 4.0.2 on 2022-03-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_interest_profile'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_model',
            name='members',
            field=models.ManyToManyField(to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='group',
            field=models.ManyToManyField(to='group.Group_model'),
        ),
    ]
