# Generated by Django 4.0.2 on 2022-03-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_model_members_alter_interest_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_model',
            name='date_meeting',
            field=models.DateField(null=True),
        ),
    ]
